# Generated by Django 3.2.5 on 2021-08-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_online', '0002_auto_20210809_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books_online.library'),
        ),
        migrations.AddField(
            model_name='library',
            name='category_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='library',
            name='shelve_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelve',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books_online.library'),
        ),
    ]
