# Generated by Django 3.2.5 on 2021-08-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_online', '0003_auto_20210809_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='temporary_book',
            name='author',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='temporary_book',
            name='published_city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='temporary_book',
            name='publisher',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='temporary_book',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
