# Generated by Django 3.2.5 on 2021-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_online', '0004_auto_20210812_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='many_to_many',
            field=models.ManyToManyField(blank=True, null=True, to='books_online.BookCategory'),
        ),
    ]
