# Generated by Django 3.2.5 on 2021-08-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_online', '0005_book_many_to_many'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='many_to_many',
            new_name='categories_fk',
        ),
    ]
