# Generated by Django 3.2.5 on 2021-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_online', '0006_rename_many_to_many_book_categories_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
