# Generated by Django 3.2.5 on 2021-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_online', '0007_alter_bookcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories_fk',
            field=models.ManyToManyField(blank=True, to='books_online.BookCategory'),
        ),
    ]
